### ISSUE TITLE
cannot override id

### ISSUE THREAD

**Issue by scivm** [ThibaultReuille/semanticnet#12]
The follow code:
# !/usr/bin/python

import sys
import semanticnet as sn
graph = sn.Graph()
a = graph.add_node({"label" : "A", "id": 0})
graph.save_json("output.json")

results in:

{
 "timeline": [], 
 "nodes": [
  {
   "id": "c2f0786f1ba5482b9496c7642f6482e0", 
   "label": "A"
  }
 ], 
 "meta": {}, 
 "edges": []

id override is not working.

**Comment by scivm** [comment]
workaround is like this:
        gtemp = graph.networkx_graph()
        gtemp.add_node(nodename)
        graph.load_networkx_graph(gtemp)
The "nodename" becomes the id.

**Comment by ThibaultReuille** [comment]
Hi scivm,

As you can see in the documentation, if you want to use your custom IDs, you should do it like this :

a = g.add_node({"type": "server"}, '3caaa8c09148493dbdf02c574b95526c')

The ID should be the 2nd argument. It isn't part of the attributes dictionary ;).
Hope this helps.

**Comment by scivm** [comment]
On the front page it does look like id is an attribute from this:

Vertex 0 has the attributes: {"type": "A", "id": 0}
Vertex 1 has the attributes: {"type": "B", "id": 1}
Vertex 2 has the attributes: {"type": "C", "id": 2}
Edge (0, 1) has the attributes: {'src': 0, 'dst': 1, 'type': 'normal', 'id': 0}
Edge (0, 2) has the attributes: {'src': 0, 'dst': 2, 'type': 'normal', 'id': 1}
Edge (1, 2) has the attributes: {'src': 1, 'dst': 2, 'type': 'irregular', 'id': 1}

but I do see in the caching section the method you describe.

Thanks.  I like the software.

**Comment by dead10ck** [comment]
@scivm the ID _is_ an attribute, but you're not supposed to set it directly. `semanticnet` manages the `id` attribute--internally, the `add_node()` method takes the ID given by the optional `id_` parameter and overwrites the `id` attribute of the node with it. If the `id_` parameter is not given, it uses a randomly-generated UUID. Sorry for the confusion.

**Comment by dead10ck** [comment]
@scivm just FYI, I've pushed an update. Semanticnet will now raise an exception if you try to set any reserved fields in `add_node()` or `add_edge()`. Reserved fields are `id`, `src`, and `dst`. You can update with `pip install --upgrade semanticnet`. This should make it clearer to users when they are using a field they shouldn't be, and should avoid future issues with this.
