### ISSUE TITLE
ModuleNotFoundError: No module named 'Graph'

### ISSUE THREAD

**Issue by seanbutler** [ThibaultReuille/semanticnet#16]
Hi, 

I installed semanticnet using 'pip install' on widows over win-python 3.6 to evaluate it for a video retrieval system but am experiencing installation issues. Perhaps its a bug, perhaps there is a clash with another python library, im really not experienced enough at pythonic libraries to speculate or fix.
Any thoughts?
Sean

knowledge.py looks like this

```
import semanticnet as sn
print ("\nSEMANTIC NETWORK EXP\n")
g1 = sn.Graph()
n1 = g1.add_node({ "label" : "man" })
n2 = g1.add_node({ "label" : "walk" })
g1.add_edge(n1, n2, { "label" : "AGENT" })
```

command and output looks like this
```
c:\...\project\> python .\knowledge.py
Traceback (most recent call last):
  File ".\knowledge.py", line 1, in <module>
    import semanticnet as sn
  File "C:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\semanticnet\__init__.py", line 1, in <module>
    from Graph import *
ModuleNotFoundError: No module named 'Graph'
```

**Comment by dead10ck** [comment]
Hi @seanbutler. I believe the problem you are encountering is that `semanticnet` is only compatible with Python 2. It should be able to import if you run your script with a Python 2 interpreter.

**Comment by seanbutler** [comment]
Thanks!
